Added new features for battery module cards
GeorgeCimpoeru/PoC pull request #107
Opened 2024-06-28 09:24 UTC by amalia94

2024-06-28 09:31 UTC, Elisei-26 commented on src/front_end/carsdata/app/batteryModule/page.tsx
> +import PercentageCard from '../components/batteryComponents/PercentageCard'
all imports should have ; at the end of row

2024-06-28 09:46 UTC, Elisei-26 requested changes

2024-06-28 09:46 UTC, Elisei-26 commented on src/front_end/carsdata/app/batteryModule/page.tsx
> +import PercentageCard from '../components/batteryComponents/PercentageCard'
all imports should have ; at the end of row

2024-06-28 09:46 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/BatteryStateCard.tsx
> +
; at the end of import import rows and add the .js extension in animation path

2024-06-28 09:46 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/BatteryStateCard.tsx
> +            setInputValue(value)
delete the id parameter, it is not used

2024-06-28 09:46 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/Charging_time.tsx
> +import Modal from '../sharedComponents/ModalString'
; at the end of import rows, .js estension for animation path, keep the camel case pattern for animations file name

2024-06-28 09:46 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/Charging_time.tsx
> +      const handleInputChange = (value: any, id: string) => {
delete id parameter

2024-06-28 09:46 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/DeviceConsumption.tsx
> +import ModalDigit from '../sharedComponents/ModalDigit';
; at the end of import rows, .js estension for animation path, keep the camel case pattern for animations file name

2024-06-28 09:46 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/FullyChargedCard.tsx
> +import BatteryFully from '../animations/batteryFully'
; at the end of import rows, .js estension for animation path

2024-06-28 09:46 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/LifeCycleCard.tsx
> +import Modal from '../sharedComponents/ModalString'
; at the end of import rows, .js estension for animation path

2024-06-28 09:46 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/LifeCycleCard.tsx
> +      const handleInputChange = (value: any, id: string) => {
delete id parameter

2024-06-28 09:46 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/PercentageCard.tsx
> +import ModalString from '../sharedComponents/ModalString'
; at the end of import rows

2024-06-28 09:46 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/RangeBatteryCard.tsx
> +import Other from '../animations/other'
; at the end of import rows, .js estension for animation path

2024-06-28 09:46 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/SerialNumberCard.tsx
> +import Modal from '../sharedComponents/ModalString';
; at the end of import rows, .js estension for animation path

2024-06-28 09:46 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/SerialNumberCard.tsx
> +      const handleInputChange = (value: any, id: string) => {
delete  id parameter

2024-06-28 09:46 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/TemperatureCard.tsx
> +import Modal from '../sharedComponents/ModalString'
; at the end of import rows, .js estension for animation path

2024-06-28 09:46 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/TemperatureCard.tsx
> +      const handleInputChange = (value: any, id: string) => {
delete id parameter

2024-06-28 09:46 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/VoltageCard.tsx
> +import ModalString from '../sharedComponents/ModalString';
; at the end of import rows

2024-06-28 09:46 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/VoltageCard.tsx
> +      const handleInputChange = (value: any, id: string) => {
delete id parameter

2024-06-28 09:46 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/sharedComponents/ModalString.tsx
> +            props.handleInputChange(event.target.value, props.id);
delete props.id parameter

2024-06-28 09:54 UTC, Elisei-26 requested changes

2024-06-28 09:54 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/Charging_time.tsx
> +            setInputValue(value)
delete the id parameter, it is not used, ad ; at the end of line 9

2024-06-28 09:54 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/DeviceConsumption.tsx
> +            setInputValue(value)
; at the end of line

2024-06-28 09:54 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/FullyChargedCard.tsx
> +                  setstatus('off')
; at the end of line

2024-06-28 09:54 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/LifeCycleCard.tsx
> +            setInputValue(value)
delete the id parameter, it is not used, ad ; at the end of line 9

2024-06-28 09:54 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/PercentageCard.tsx
> +            setInputValue(value)
delete the id parameter, it is not used, ad ; at the end of line 9

2024-06-28 09:54 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/RangeBatteryCard.tsx
> +                  setstatus('off')
; at the end of line

2024-06-28 09:54 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/SerialNumberCard.tsx
> +            setInputValue(value)
; at the end of line

2024-06-28 09:54 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/TemperatureCard.tsx
> +            setInputValue(value)
delete the id parameter, it is not used, ad ; at the end of line 9

2024-06-28 09:54 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/VoltageCard.tsx
> +            setInputValue(value)
delete the id parameter, it is not used, ad ; at the end of line 9

2024-06-28 09:56 UTC, Elisei-26 requested changes

2024-06-28 09:56 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/animations/charging_time.js
> +import "./style.css"
; at the end of all styles imports

2024-06-28 10:37 UTC, Elisei-26 requested changes

2024-06-28 10:37 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/animations/rangeBattery.js
>  import "./style.css"
add ; to all import rows in all files

2024-06-28 10:37 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/BatteryStateCard.tsx
>  'use client'
; here too

2024-06-28 10:37 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/Charging_time.tsx
>              setInputValue(value)
forgot ;

2024-06-28 10:37 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/LifeCycleCard.tsx
>              setInputValue(value)
forgot ;

2024-06-28 10:37 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/PercentageCard.tsx
>              setInputValue(value)
forgot ;

2024-06-28 10:37 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/RangeBatteryCard.tsx
>                    setstatus('on');
; line 11

2024-06-28 10:37 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/TemperatureCard.tsx
>              setInputValue(value)
forgot ;

2024-06-28 10:37 UTC, Elisei-26 commented on src/front_end/carsdata/app/components/batteryComponents/VoltageCard.tsx
>              setInputValue(value)
forgot ;

2024-06-28 10:54 UTC, Elisei-26 approved these changes

2024-07-01 06:42 UTC, GeorgeCimpoeru approved these changes

2024-07-01 06:42 UTC, merged