Tester Present Service
GeorgeCimpoeru/PoC pull request #111
Opened 2024-06-28 15:01 UTC by alexandrudoncea

Implementation of Tester Present Service. --> INCOMPLETE

Created the TesterPresent class within TesterPresent.h and TesterPresent.cpp

monitorTesterPresence method checks if the S3 timer ran out.

handleReceivedFrame method check if the received frame from CANBus is the specific one for this service (0x3E) and sends back the response (0x7E).

The only things that are left to do:
- integration in a module (I suppose MCU)
- testing the implementation to check if everything works correctly

2024-07-04 09:06 UTC, TheoRandstad reviewed
Please solve the conflicts:)

2024-07-26 13:27 UTC, Mihnea9901 commented on src/uds/tester_present/test/TesterPresentTest.cpp
> + * @brief Unit test for TesterPresent service
can you let the file in the utest folder instead of test?
all other services are in utest

2024-07-26 13:27 UTC, Mihnea9901 commented on src/uds/read_data_by_identifier/include/ReadDataByIdentifier.h
> +#include "../../../utils/include/Logger.h"
restore this

2024-07-26 13:27 UTC, Mihnea9901 commented on src/uds/authentication/include/SecurityAccess.h
> +#include "../../../utils/include/Logger.h"
restore this

2024-07-26 13:27 UTC, Mihnea9901 commented on src/rest_api/app/requirements.txt
restore this so it does not appear here

2024-07-26 13:28 UTC, Mihnea9901 commented on src/ota/transfer_data/include/TransferData.h
> +#include "../../../utils/include/Logger.h"
restore this

2024-07-26 13:29 UTC, Mihnea9901 commented on src/mcu/include/ReceiveFrames.h
> +  std::queue<struct can_frame> frame_queue;
all of these lines should have indentation

2024-07-26 14:04 UTC, Mihnea9901 approved these changes

2024-08-01 09:07 UTC, Mihnea9901 requested changes
After you come back from holiday, please pull rebase from UDS branch and accept makefiles from the UDS branch.
Theodor improved the entire makefile. If you need help adding your own test job and file to be compiled please contact him.

2024-08-02 12:42 UTC, GeorgeCimpoeru commented
Too many time whit this pull request in progress. 
Please close it with a proper comment and redo it !

2024-08-07 06:30 UTC, closed without merging