Read info doors
GeorgeCimpoeru/PoC pull request #166
Opened 2024-07-12 08:40 UTC by BogdanRandstad

Added features for reading doors.
Implemented a specific class.
Implemented the respective api route and update html syntax and javascript for adding read from doors option

2024-07-12 10:39 UTC, CatalinGP approved these changes

2024-07-12 10:45 UTC, asavu91 approved these changes

2024-07-15 07:24 UTC, RubenNatanael requested changes

2024-07-15 07:24 UTC, RubenNatanael commented on src/rest_api/actions/read_info_action.py
> +        self._passive_response(SESSION_CONTROL, "Error changing session control")
Is better if this two lines are added in to the try block, if an exception is throw from the response method.

2024-07-15 07:24 UTC, RubenNatanael commented on src/rest_api/actions/read_info_action.py
> +
The identifiers must be put in the config file. Don't use dummy identifiers, set specific ones with your colleagues.

2024-07-15 08:01 UTC, BogdanRandstad commented on src/rest_api/actions/read_info_action.py
> +
The identifiers for doors don't exist on UDS side. Temporary will use dummy values.

2024-07-16 07:43 UTC, RubenNatanael commented on src/rest_api/actions/read_info_action.py
> +
You can set specific ones like in the battery module

2024-07-17 09:36 UTC, closed without merging