Write to doors
GeorgeCimpoeru/PoC pull request #231
Opened 2024-07-29 10:41 UTC by asavu91

- implemented a class WriteInfo that inherits from the Action class and provides functionality to write data
- created a JavaScript function writeInfoDoors which prompts the user to insert door parameter.
- created the POST endpoint in flask.

2024-07-30 08:31 UTC, CatalinGP requested changes
review my code comments.

2024-07-31 18:05 UTC, CatalinGP requested changes
please review my comments

2024-07-31 18:05 UTC, CatalinGP commented on src/rest_api/actions/write_info_action.py
> +    def _write_by_identifier(self, id, identifier, value):
make use of write_by_identifier from generate_frames.py

2024-07-31 18:05 UTC, CatalinGP commented on src/rest_api/actions/write_info_action.py
> +class WriteToDoors(WriteInfo):
i thought we discussed to have methods inside WriteInfo class for write_to_bat, write_to_engine, write_to_doors...

2024-08-02 06:17 UTC, CatalinGP approved these changes

2024-08-02 06:39 UTC, Mihnea9901 approved these changes

2024-08-02 06:39 UTC, merged