Feature/ota integrate google drive with request download
GeorgeCimpoeru/PoC pull request #241
Opened 2024-08-01 06:54 UTC by IDaniel99

Added python class for file management in google drive, using the Google Drive API:
- upload files
- download files
- update drive data => get an overview of the folders/files on the google drive as a json in order to see what versions are for which mcu/ecu

RequestDownload changes: 
- included pybind11 library for integrating python code in c++
- added downloadSoftwareVersion method that downloads a file with a specific id from the drive

Makefile MCU changes:
- added python cflags and ldflags needed for pybind library

2024-08-01 10:54 UTC, CatalinGP requested changes
Please review my comment.

2024-08-01 10:54 UTC, CatalinGP commented on .github/workflows/build_checker.yml
> +          python3 setup.py
use "python3.8 setup.py" to ensure the specific version of python used within the project.

2024-08-01 11:40 UTC, CatalinGP approved these changes

2024-08-02 08:56 UTC, Mihnea9901 approved these changes

2024-08-02 10:29 UTC, CatalinGP approved these changes

2024-08-02 10:30 UTC, merged