Post Service - update to version - done
GeorgeCimpoeru/PoC pull request #280
Opened 2024-08-13 12:29 UTC by amalia94

## Description

-add new components for upgrade and downgrade;
-change the design for OTA page 
-create a table for version control & other info 

## Trello link [here](https://trello.com/c/X8uEqbij/46-post-service-update-version-continue)

## Type of change

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-08-13 12:50 UTC, TheoRandstad approved these changes

2024-08-14 07:12 UTC, Elisei-26 requested changes

2024-08-14 07:12 UTC, Elisei-26 commented on src/rest_api/utils/scripts/update_to.sh
> +cansend vcan1 000011FA#0462F1AD
we don't have to modify things from the API

2024-08-14 07:34 UTC, Elisei-26 approved these changes

2024-08-14 07:35 UTC, merged