Feature/ecu doors module d
GeorgeCimpoeru/PoC pull request #346
Opened 2024-08-29 12:33 UTC by lodug

## Description

Implemented the draft for doors module and integrated it into services.

## Trello link [here](https://trello.com/c/u3Kw3XoC/29-create-draft-implementation-for-doors-ecu)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-08-29 14:19 UTC, Mihnea9901 commented on src/ecu_simulation/DoorsModule/include/DoorsModule.h
> +        {0x03A0, {0}},  /* Driver Door Status */
why do we need this map if we use RDBI and WDBI to files?
same for other modules, @DirvaNIcolae

2024-08-29 14:26 UTC, Mihnea9901 commented on src/uds/clear_dtc/src/ClearDtc.cpp
> +        else if (lowerbits == 0x13) {
can't we have this switch case that is present anywhere to be used only once instead of using it every time we send a response, so we avoid duplicate code?
same for other modules already merged @DirvaNIcolae 

it applies to all services where this is used, it's not ok to call this switch case 1000 times in a service

2024-08-29 14:43 UTC, Mihnea9901 requested changes

2024-08-29 14:43 UTC, Mihnea9901 commented on src/ecu_simulation/DoorsModule/src/DoorsModule.cpp
> +        std::map<uint16_t,std::string> updated_values =
wasn't this supposed to move into files?
so RDBI and WDBI will be used to read/write into files?

2024-08-29 14:50 UTC, Mihnea9901 commented on src/ecu_simulation/DoorsModule/include/DoorsModule.h
> +    void fetchDoorsData();
maybe setDoorsData instead of fetch? because you set default values, you don't fetch them from somewhere

2024-08-29 14:51 UTC, Mihnea9901 commented on src/ecu_simulation/DoorsModule/src/DoorsModule.cpp
> +        /* std::cerr << "Error fetching doors data: " << e.what() << std::endl; */
remove cerr line

2024-08-29 14:55 UTC, Mihnea9901 requested changes

2024-08-29 14:55 UTC, Mihnea9901 commented on src/ecu_simulation/DoorsModule/include/DoorsModule.h
> +    bool doorDriverOpen;
why do we need this parameters here?
we moved RDBI and WDBI to files, this data should be mapped to some DIDS and stored into files.

2024-08-30 06:43 UTC, DirvaNIcolae commented on src/ecu_simulation/DoorsModule/include/DoorsModule.h
> +        {0x03A0, {0}},  /* Driver Door Status */
We need this map to insert the default DIDs into the files. However, this variable can be moved to the constructor so it doesn't occupy memory unnecessarily.

2024-08-30 06:49 UTC, DirvaNIcolae commented on src/uds/clear_dtc/src/ClearDtc.cpp
> +        else if (lowerbits == 0x13) {
Sure, we'll improve the code in the services to eliminate the duplicate code.

2024-08-30 06:51 UTC, Mihnea9901 commented on src/ecu_simulation/DoorsModule/include/DoorsModule.h
> +        {0x03A0, {0}},  /* Driver Door Status */
But you already declare another map in DoorsModule.cpp line 122, that is used to insert into files.
Why not make a single setUp method that is called at the start of module and it sets the default values?

2024-08-30 06:54 UTC, lodug commented on src/ecu_simulation/DoorsModule/include/DoorsModule.h
> +        {0x03A0, {0}},  /* Driver Door Status */
It was a mistake from my side. The code needs modifications.

2024-08-30 07:20 UTC, lodug commented on src/ecu_simulation/DoorsModule/include/DoorsModule.h
> +    bool doorDriverOpen;
These parameters will be deleted

2024-08-30 12:07 UTC, Mihnea9901 approved these changes

2024-08-30 12:07 UTC, alexandrudoncea approved these changes

2024-08-30 12:07 UTC, merged