implemented ReadMemoryByAddress
GeorgeCimpoeru/PoC pull request #347
Opened 2024-08-29 13:41 UTC by alexandrudoncea

## Description

Implementation of Read Memory by Address service for UDS. In this implementation I used the MemoryManager class to help me develop the methods. I also implemented the case where the response is separated in multiple frames. 
I did not manage to make this service read something from a real address so I tested on simulated data and address and it works well. I think this service will work as it should when the project will be running on Raspberries. 

## Trello link [here](https://trello.com/c/k0aie0DF)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-08-29 14:40 UTC, Mihnea9901 commented on src/utils/src/HandleFrames.cpp
> +                GenerateFrames frameGenerator(recv_frames.getMcuSocket(frame_id), _logger);
you don't need any receive_frames obj in handleFrames.
the socket is already initialized in handleFrames constructor and it is a member of handleFrames class. you can use that socket

2024-08-29 14:59 UTC, Mihnea9901 requested changes

2024-08-29 14:59 UTC, Mihnea9901 commented on src/uds/read_memory_by_address/src/ReadMemoryByAddress.cpp
> +        frameGenerator.negativeResponse(can_id, 0x23, 0x13); // Sending Negative Response for invalid address/size
Use negative response service instead of generateFrames

2024-08-29 14:59 UTC, Mihnea9901 commented on src/uds/read_memory_by_address/src/ReadMemoryByAddress.cpp
> +
add check for message length
If not ok return IMLOIF

2024-08-29 14:59 UTC, Mihnea9901 commented on src/uds/read_memory_by_address/src/ReadMemoryByAddress.cpp
> +
add check for security
if not ok return SAD NRC

2024-08-30 03:09 UTC, TheoRandstad requested changes
Build checker failed

2024-08-30 11:07 UTC, Mihnea9901 approved these changes

2024-08-30 11:07 UTC, merged