Feature/ecu doors module d
GeorgeCimpoeru/PoC pull request #360
Opened 2024-08-30 13:38 UTC by alexandrudoncea

## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context.

## Trello link [here](put here the link)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-08-30 13:39 UTC, Mihnea9901 approved these changes

2024-08-30 13:39 UTC, Mihnea9901 approved these changes

2024-09-02 04:25 UTC, TheoRandstad requested changes
Build failded. All branches got messed up. Wait until my PR for backend fix is merged.

2024-09-02 10:40 UTC, TheoRandstad commented
This PR need rebase

2024-09-07 08:39 UTC, closed without merging