refactoring Loading
GeorgeCimpoeru/PoC pull request #483
Opened 2024-10-16 09:38 UTC by MihaelaDraga

## Description

A code refactory was made for Loading

2024-10-17 12:30 UTC, Elisei-26 approved these changes

2024-10-17 13:12 UTC, TheoRandstad reviewed
Please respect the model of the template

2024-10-18 07:17 UTC, DanielConstantinescu requested changes

2024-10-18 07:52 UTC, MihaelaDraga commented on src/front_end/carsdata/src/components/UDScomponents/DivCenterBattery.tsx
> +                displayErrorPopup("Connection failed");
Done!

2024-10-18 07:52 UTC, MihaelaDraga commented on src/front_end/carsdata/src/components/UDScomponents/DivCenterDoors.tsx
> +                    displayErrorPopup("Connection failed");
Done

2024-10-22 12:11 UTC, closed without merging